name: MOVIL WORKFLOW

on:
  push:
    branches:
      - '*'    
  pull_request:
    branches:
      - main   
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
          cache: 'npm'  

      - name: Install dependencies
        run: npm ci

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Build Ionic App
        run: ionic build

      - name: Serve built app
        run: npx http-server ./www -p 8100 -a localhost &
        env:
          CI: true

      - name: Wait for app server to be available
        run: npx wait-on http://localhost:8100 --timeout 600000 # Espera hasta 10 minutos

      - name: Start server and run Cypress
        run: npx start-server-and-test "ionic build && npx http-server ./www -p 8100" http://localhost:8100 "cypress run"
      
      # 8. Ejecutar Linter
      - name: Run lint
        run: npm run lint 
        
      - name: Run Karma tests
        run: npm run test 

      - name: e2e cypress
        run: npx cypress run
